<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Character Encoding -->
    <meta charset="UTF-8">
    
    <!-- Viewport for Responsive Design (Mobile First) -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Page Title: Descriptive of the functionality -->
    <title>Matrix Generated by Nested 'for' Loop</title>

    <!-- External Stylesheet -->
    <link rel="stylesheet" type="text/css" href="Styles/styles.css">

    <!-- Author Information (for personal tracking or SEO) -->
    <meta name="author" content="Ambel Basha">

    <!-- Description of the Page (SEO optimization) -->
    <meta name="description" content="This page demonstrates the generation of a 12x12 matrix using a nested PHP 'for' loop.">

    <!-- Keywords for SEO optimization -->
    <meta name="keywords" content="PHP, Nested Loop, Matrix, Web Development, Programming">
    
</head>
<body>

    <!-- Main Content Wrapper -->
    <div class="outer-container">
        
        <!-- Inner Content Container -->
        <div class="container">
            <h3>Matrix Generated Using Nested 'for' Loop:</h3>
            
            <!-- Table Wrapper Box -->
            <div class="box">
                <table>
                    <?php
                        // Initialize counter to 1
                        $counter = 1;
                        
                        // Loop through rows (12 rows)
                        for ($i = 1; $i <= 12; $i++) {
                            echo "<tr>"; // Start a new row
                            
                            // Loop through columns (12 columns per row)
                            for ($j = 1; $j <= 12; $j++) {
                                // Display the current counter value inside each cell
                                echo "<td>" . $counter . "</td>"; 
                                
                                // Increment the counter for the next cell
                                $counter++; 
                            }
                            
                            echo "</tr>"; // End the current row
                        }
                    ?>
                </table>
            </div>
        </div>

        <!-- Return Button (for navigation back to the homepage) -->
        <div class="return-button">
            <button onclick="window.location.href='../index.html'">Back</button>
        </div>
    </div>

</body>
</html>
